import MarketingNav from '@/components/marketing/MarketingNav';
import MarketingFooter from '@/components/marketing/MarketingFooter';
import type { Metadata } from 'next';

export const metadata: Metadata = { title: 'Terms of Service' };

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#faf9f7]">
      <MarketingNav />

      <div className="max-w-[700px] mx-auto px-8 pt-16 pb-20">
        <h1 className="text-[36px] font-bold text-[#1a1a1a] mb-2">Terms of Service</h1>
        <p className="text-[14px] text-[#808080] mb-10">Last updated: March 29, 2026</p>

        <div className="prose prose-sm max-w-none text-[#444] leading-relaxed [&_h2]:text-[18px] [&_h2]:font-semibold [&_h2]:text-[#1a1a1a] [&_h2]:mt-8 [&_h2]:mb-3 [&_p]:mb-4 [&_ul]:mb-4 [&_li]:mb-1">
          <p>These Terms of Service (&ldquo;Terms&rdquo;) govern your use of Structr, an AI-powered wireframe builder operated at structr.holy.black (the &ldquo;Service&rdquo;). By using the Service, you agree to these Terms.</p>

          <h2>1. Account Registration</h2>
          <p>You must provide a valid email address and create a password to use the Service. You are responsible for maintaining the security of your account credentials. You must be at least 16 years old to create an account.</p>

          <h2>2. Star Credits</h2>
          <p>The Service uses an internal currency called &ldquo;stars&rdquo; for AI-powered features. Free accounts receive 50 stars upon registration. Stars are consumed when you use AI features such as project generation, page import, and section editing. Star costs are displayed before each action.</p>
          <p>Stars have no cash value and cannot be transferred between accounts, refunded, or exchanged for money. We reserve the right to adjust star costs and allocation at any time.</p>

          <h2>3. Acceptable Use</h2>
          <p>You agree not to:</p>
          <ul>
            <li>Use the Service to generate illegal, harmful, or abusive content</li>
            <li>Attempt to circumvent star credit limits or usage restrictions</li>
            <li>Use automated tools to bulk-generate content or abuse the AI features</li>
            <li>Impersonate others or misrepresent your affiliation</li>
            <li>Interfere with or disrupt the Service or its infrastructure</li>
            <li>Reverse-engineer the Service or access non-public APIs</li>
          </ul>

          <h2>4. Your Content</h2>
          <p>You retain ownership of the wireframe projects you create. By using the Service, you grant us a limited license to store, process, and display your content as needed to provide the Service (including sending content to Anthropic for AI processing).</p>
          <p>Published projects are publicly accessible. You are responsible for the content you publish.</p>

          <h2>5. AI-Generated Content</h2>
          <p>Content generated by AI features is provided &ldquo;as-is&rdquo; and may not be accurate, complete, or suitable for your needs. You are responsible for reviewing and editing AI-generated content before publishing or using it commercially. We do not guarantee the quality, accuracy, or originality of AI-generated content.</p>

          <h2>6. Service Availability</h2>
          <p>We strive to keep the Service available 24/7 but do not guarantee uninterrupted access. We may perform maintenance, updates, or modifications that temporarily affect availability. We will try to provide advance notice for planned downtime.</p>

          <h2>7. Intellectual Property</h2>
          <p>The Service, including its design, code, section templates, and AI prompts, is owned by Structr. You may not copy, modify, or distribute the Service itself. Your wireframe projects and their content belong to you.</p>

          <h2>8. Termination</h2>
          <p>You may delete your account at any time. We may suspend or terminate your account if you violate these Terms. Upon termination, your projects and data will be deleted after 30 days. You can export your data before termination using the JSON export feature.</p>

          <h2>9. Limitation of Liability</h2>
          <p>The Service is provided &ldquo;as-is&rdquo; without warranties of any kind. We are not liable for any indirect, incidental, or consequential damages arising from your use of the Service. Our total liability is limited to the amount you have paid us in the 12 months preceding the claim.</p>

          <h2>10. Changes to Terms</h2>
          <p>We may update these Terms from time to time. Continued use of the Service after changes constitutes acceptance of the new Terms. We will notify you of material changes via email or in-app notification.</p>

          <h2>11. Contact</h2>
          <p>For questions about these Terms, please contact us at legal@holy.gd.</p>
        </div>
      </div>

      <MarketingFooter />
    </div>
  );
}
